# Generated by Django 3.2 on 2023-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230506_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='habilidades',
        ),
        migrations.AddField(
            model_name='perfil',
            name='habilidades',
            field=models.ManyToManyField(to='api.Habilidade'),
        ),
    ]
