# Generated by Django 3.2 on 2023-05-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230506_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AlterModelOptions(
            name='habilidade',
            options={'verbose_name_plural': 'Habilidades'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='servico',
            options={'verbose_name_plural': 'Serviços'},
        ),
    ]
